# Generated by Django 4.1 on 2023-01-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polybookexchange", "0003_alter_author_id_alter_candidate_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    models.CharField(
                        choices=[("exchange_location", "Location of the exchange"), ("exchange_time", "Time of the exchange")],
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("text_fr", models.TextField()),
                ("text_en", models.TextField()),
            ],
        ),
    ]
