# Generated by Django 4.1 on 2023-01-15 17:22

from django.db import migrations


def create_texts(apps, schema_editor):
    Text = apps.get_model("polybookexchange", "Text")

    Text(key="exchange_time", text_en="Mon-Fri from 10am to 4pm", text_fr="du lundi au vendredi de 10h à 16h").save()
    Text(key="exchange_location", text_en="at AGEPoly's desk", text_fr="à la boutique de l'AGEPoly").save()


class Migration(migrations.Migration):

    dependencies = [
        ("polybookexchange", "0004_text"),
    ]

    operations = [
        migrations.RunPython(create_texts),
    ]
