name: Formatting

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Check formatting
        run: |
            pip install -U pip
            pip install -U black isort
            black --check .
            isort --check-only --diff .
